
create table if not exists carnumbers
(
    id              int8 generated by default as identity,
    prefix          varchar(1),
    num             int8,
    suffix          varchar(1),
    postfix         varchar(1),
    representation  varchar(6)
);