create table if not exists carnumbers
(
    id             int8 generated by default as identity,
    prefix         char(1),
    num            int4,
    suffix         char(1),
    postfix        char(1),
    representation varchar(6)
);